package com.kathirha.domain;

public enum InsightKind {
    PERSONALITY, HEALTH_SCORE, ANOMALY, CASHBACK, BUDGET, LEADERBOARD_EXPLAIN,
    PAYDAY, STREAK_COACH, REWARD_REC, ADMIN_INSIGHT, GOAL_PLAN, GOAL_RESCUE, SAVING_INSIGHT
}
